const fs = require('fs');
const path = require('path');
const dayjs = require('dayjs');
const PDFDocument = require('pdfkit');

async function generateMOMPDF({ mom, workspace, generatedBy, filePath }) {
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(filePath);
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
    doc.on('error', reject);
    doc.pipe(stream);

    doc.fontSize(18).text('Minutes of Meeting', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`MOM No: ${mom.momNumber}`);
    doc.text(`Title: ${mom.title}`);
    doc.text(`Meeting Date: ${mom.meetingDate ? dayjs(mom.meetingDate).format('DD-MM-YYYY') : '-'}`);
    doc.text(`Time: ${mom.startTime || ''} - ${mom.endTime || ''}`);
    doc.text(`Location/Link: ${mom.location || mom.meetingLink || '-'}`);
    doc.moveDown();

    doc.fontSize(14).text('Agenda', { underline: true });
    doc.fontSize(10).text(mom.agenda || '-');
    doc.moveDown();

    doc.fontSize(14).text('Attendees', { underline: true });
    (mom.attendees || []).forEach((attendee, index) => {
      doc.fontSize(10).text(`${index + 1}. ${attendee.name || ''} | ${attendee.email || ''} | ${attendee.signed ? 'Signed' : 'Pending'}`);
    });
    doc.moveDown();

    doc.fontSize(14).text('Discussion Points', { underline: true });
    (mom.discussionPoints || []).forEach((point, index) => {
      doc.fontSize(10).text(`${index + 1}. ${point.title || '-'}`);
      if (point.description) doc.text(`   ${point.description}`);
    });
    doc.moveDown();

    doc.fontSize(14).text('Decisions', { underline: true });
    (mom.decisions || []).forEach((decision, index) => {
      doc.fontSize(10).text(`${index + 1}. ${decision.decision || '-'}`);
    });
    doc.moveDown();

    doc.fontSize(14).text('Action Points', { underline: true });
    (mom.actionPoints || []).forEach((point) => {
      doc.fontSize(10).text(
        `${point.pointNumber || ''}. ${point.title} | Target: ${point.targetDate ? dayjs(point.targetDate).format('DD-MM-YYYY') : '-'} | Status: ${point.status}`
      );
    });
    doc.moveDown();

    doc.fontSize(14).text('Signatures', { underline: true });
    (mom.attendees || [])
      .filter((attendee) => attendee.signatureRequired !== false)
      .forEach((attendee) => {
        doc.fontSize(10).text(
          `${attendee.name || attendee.email || '-'} - ${
            attendee.signed ? `Signed on ${dayjs(attendee.signedAt).format('DD-MM-YYYY hh:mm A')}` : 'Pending'
          }`
        );
      });

    doc.moveDown();
    doc.fontSize(8).text('Generated by ONEPWS Marketing Workflow System | Confidential Internal Document', { align: 'center' });
    doc.fontSize(8).text(`Generated at ${dayjs().format('DD-MM-YYYY hh:mm A')} by ${generatedBy || ''}`, { align: 'center' });
    doc.end();
  });
}

module.exports = { generateMOMPDF };
