/**
 * reportEmail.service.js - Send Reports via Email
 */

const nodemailer = require('nodemailer');
const path = require('path');

/**
 * Get email transporter configuration
 */
const getEmailTransporter = () => {
  // Configuration from .env or environment
  const emailConfig = {
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: process.env.EMAIL_PORT || 587,
    secure: process.env.EMAIL_SECURE === 'true', // true for 465, false for 587
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASSWORD
    }
  };

  return nodemailer.createTransport(emailConfig);
};

/**
 * Send Report Email with PDF attachment
 * 
 * @param {Object} options
 * @param {Array} options.to - Recipient email addresses
 * @param {String} options.subject - Email subject
 * @param {String} options.message - Optional personal message
 * @param {String} options.senderName - Name of person sending
 * @param {Number} options.taskCount - Count of items in report
 * @param {Buffer} options.pdfBuffer - PDF file buffer
 * @param {String} options.fileName - Attachment filename
 */
const sendReportEmail = async (options) => {
  const {
    to,
    subject,
    message,
    senderName,
    taskCount,
    pdfBuffer,
    fileName
  } = options;

  try {
    const transporter = getEmailTransporter();

    // Build HTML email template
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            body { font-family: Arial, sans-serif; background-color: #f5f5f5; }
            .container { max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .header { background-color: #D32F2F; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
            .header h1 { margin: 0; font-size: 24px; }
            .header p { margin: 5px 0 0 0; font-size: 14px; opacity: 0.9; }
            .content { padding: 30px; }
            .content p { margin: 10px 0; line-height: 1.6; color: #333333; }
            .stats { background-color: #f9f9f9; border-left: 4px solid #D32F2F; padding: 15px; margin: 20px 0; border-radius: 4px; }
            .stats p { margin: 5px 0; font-size: 14px; }
            .message-box { background-color: #e8f4f8; padding: 15px; border-radius: 4px; margin: 20px 0; border-left: 4px solid #2196F3; }
            .footer { background-color: #f5f5f5; padding: 15px; text-align: center; font-size: 12px; color: #666666; border-top: 1px solid #e0e0e0; }
            .button { display: inline-block; background-color: #D32F2F; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; margin-top: 10px; }
          </style>
        </head>
        <body>
          <div class="container">
            <!-- Header -->
            <div class="header">
              <h1>ONEPWS Marketing System</h1>
              <p>Automated Report</p>
            </div>

            <!-- Content -->
            <div class="content">
              <p>Dear Team,</p>
              
              <p>Please find the attached <strong>Tasks Report</strong> with the following details:</p>

              <!-- Stats Box -->
              <div class="stats">
                <p><strong>📊 Report Summary:</strong></p>
                <p>• Total Items: <strong>${taskCount}</strong></p>
                <p>• Generated: ${new Date().toLocaleString('en-IN')}</p>
                <p>• Generated By: <strong>${senderName}</strong></p>
              </div>

              ${message ? `
              <div class="message-box">
                <strong>📝 Message from ${senderName}:</strong>
                <p>${message.replace(/\n/g, '<br>')}</p>
              </div>
              ` : ''}

              <p>
                <a href="#" class="button">View Report in ONEPWS</a>
              </p>

              <p style="margin-top: 20px; font-size: 12px; color: #999999;">
                <strong>How to use this report:</strong><br>
                • Open the PDF file to review all details<br>
                • Click the button above to access the full system<br>
                • Contact support if you have any questions
              </p>
            </div>

            <!-- Footer -->
            <div class="footer">
              <p style="margin: 0;">
                This is an automated email from ONEPWS Marketing System<br>
                <strong>© ONEPWS Private Limited</strong> | All rights reserved
              </p>
              <p style="margin: 10px 0 0 0; font-size: 11px;">
                If you have any questions or need assistance, please contact your administrator.
              </p>
            </div>
          </div>
        </body>
      </html>
    `;

    // Send email
    const mailOptions = {
      from: `ONEPWS <${process.env.EMAIL_USER}>`,
      to: to.join(', '),
      subject: subject,
      html: htmlContent,
      attachments: [
        {
          filename: fileName,
          content: pdfBuffer,
          contentType: 'application/pdf'
        }
      ]
    };

    const info = await transporter.sendMail(mailOptions);
    
    console.log(`Report email sent. Message ID: ${info.messageId}`);
    return info;
  } catch (error) {
    console.error('Email sending failed:', error);
    throw new Error(`Failed to send email: ${error.message}`);
  }
};

/**
 * Send Email with Multiple Attachments
 */
const sendEmailWithAttachments = async (options) => {
  const { to, subject, html, attachments } = options;

  try {
    const transporter = getEmailTransporter();

    const mailOptions = {
      from: `ONEPWS <${process.env.EMAIL_USER}>`,
      to: Array.isArray(to) ? to.join(', ') : to,
      subject: subject,
      html: html,
      attachments: attachments || []
    };

    const info = await transporter.sendMail(mailOptions);
    return info;
  } catch (error) {
    console.error('Email sending failed:', error);
    throw error;
  }
};

module.exports = {
  sendReportEmail,
  sendEmailWithAttachments,
  getEmailTransporter
};
