const PDFDocument = require('pdfkit');
const fs = require('fs');
const { buildReportFileName, reportUploadPath } = require('../utils/reportFileName');

const dir = reportUploadPath('pdf');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

function normalizeRows(data) {
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.rows)) return data.rows;
  if (Array.isArray(data?.tasks)) return data.tasks;
  if (Array.isArray(data?.budgets)) return data.budgets;
  if (Array.isArray(data?.expenses)) return data.expenses;
  return [];
}

function rowTitle(row, index, reportType) {
  if (reportType === 'daily_tracker') {
    return `${index + 1}. ${row.rowData?.task_number || row.task?.taskNumber || 'N/A'} | ${row.rowData?.type_of_task || 'N/A'} | ${row.rowData?.final_status || row.status || 'N/A'} | ${row.calculatedData?.delay_in_time || 'N/A'}`;
  }
  return `${index + 1}. ${row.taskNumber || row.budgetNumber || row.expenseNumber || row.title || row.name || row._id} | ${row.status || row.overallStatus || ''}`;
}

async function generatePDF({ reportType, title, data, summary = {}, filters = {}, generatedBy }) {
  const fileName = buildReportFileName({ reportType, dateFrom: filters.dateFrom, dateTo: filters.dateTo, ext: 'pdf' });
  const filePath = `${dir}/${fileName}`;

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4', bufferPages: true });
      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      doc.fontSize(18).text('ONEPWS Marketing Workflow System', { align: 'center' });
      doc.fontSize(15).text(title || reportType, { align: 'center' });
      doc.moveDown();
      doc.fontSize(9).text(`Generated At: ${new Date().toLocaleString()}`);
      if (generatedBy?.name) doc.text(`Generated By: ${generatedBy.name}`);
      if (filters.dateFrom || filters.dateTo) doc.text(`Date Range: ${filters.dateFrom || 'Start'} to ${filters.dateTo || 'Now'}`);
      doc.moveDown();

      doc.fontSize(13).text('Summary', { underline: true });
      doc.moveDown(0.5);
      Object.entries(summary || {}).slice(0, 18).forEach(([key, value]) => {
        doc.fontSize(9).text(`${key}: ${value ?? ''}`);
      });

      doc.moveDown();
      doc.fontSize(13).text('Detailed Data', { underline: true });
      doc.moveDown(0.5);
      normalizeRows(data).slice(0, 80).forEach((row, index) => {
        doc.fontSize(8).text(rowTitle(row, index, reportType), { lineGap: 2 });
      });
      if (normalizeRows(data).length > 80) doc.text(`...and ${normalizeRows(data).length - 80} more rows.`);

      const pageRange = doc.bufferedPageRange();
      for (let i = pageRange.start; i < pageRange.start + pageRange.count; i += 1) {
        doc.switchToPage(i);
        doc.fontSize(8).text(
          `Generated by ONEPWS Marketing Workflow System | Confidential Internal Report | Page ${i + 1} of ${pageRange.count}`,
          40,
          doc.page.height - 42,
          { align: 'center', width: doc.page.width - 80 }
        );
      }

      doc.end();
      stream.on('finish', () => resolve({ filePath, fileUrl: `/uploads/reports/pdf/${fileName}` }));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}

async function generateTrackerPDF({ data, summary, chartData, filters, generatedBy }) {
  return generatePDF({ reportType: 'daily_tracker', title: 'Daily Tracker Report', data, summary, chartData, filters, generatedBy });
}

module.exports = {
  generatePDF,
  generateTrackerPDF
};
