const ExcelJS = require('exceljs');
const PDFDocument = require('pdfkit');
const { ensureDefaultTrackerConfig } = require('./trackerDefaultConfig.service');
const { getTrackerRowsForReport, getSummaryReport } = require('./trackerReport.service');

const mapToObject = (value) => {
  if (!value) return {};
  if (value instanceof Map) return Object.fromEntries(value);
  if (typeof value.toObject === 'function') return value.toObject();
  return { ...value };
};

const visibleFields = (config) => [...(config.fields || [])]
  .filter((field) => field.isVisible !== false && !field.isDeleted)
  .sort((a, b) => (a.order || 0) - (b.order || 0));

const resolveValue = (row, field) => {
  const rowData = mapToObject(row.rowData);
  const calculatedData = mapToObject(row.calculatedData);
  return field.fieldType === 'auto'
    ? calculatedData[field.fieldKey]
    : rowData[field.fieldKey];
};

const writeWorkbook = async (workspaceId, user, filters = {}) => {
  const config = await ensureDefaultTrackerConfig(workspaceId, user?._id);
  const rows = await getTrackerRowsForReport(workspaceId, filters);
  const fields = visibleFields(config);
  const summary = await getSummaryReport(workspaceId, filters);

  const workbook = new ExcelJS.Workbook();
  workbook.creator = user?.name || user?.email || 'ONEPWS';
  workbook.created = new Date();

  const sheet = workbook.addWorksheet('Tracker Data', { views: [{ state: 'frozen', xSplit: 2, ySplit: 4 }] });
  sheet.mergeCells(1, 1, 1, Math.max(fields.length, 1));
  sheet.getCell(1, 1).value = 'ONEPWS - Marketing Daily Task Tracker';
  sheet.getCell(1, 1).font = { bold: true, size: 16 };
  sheet.getCell(2, 1).value = `Generated at: ${new Date().toLocaleString()}`;
  sheet.getCell(3, 1).value = `Generated by: ${user?.name || user?.email || 'System'}`;

  sheet.addRow(fields.map((field) => field.label));
  const headerRow = sheet.getRow(4);
  headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F2937' } };

  rows.forEach((row) => {
    const excelRow = sheet.addRow(fields.map((field) => resolveValue(row, field) ?? ''));
    fields.forEach((field, index) => {
      if (field.fieldKey !== 'delay_in_time') return;
      const value = String(excelRow.getCell(index + 1).value || '');
      const color = value.includes('Delayed') ? 'FFFEE2E2'
        : value.includes('On Time') ? 'FFDCFCE7'
          : value.includes('Early') ? 'FFDBEAFE'
            : value.includes('Pending') ? 'FFFEF3C7'
              : null;
      if (color) excelRow.getCell(index + 1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: color } };
    });
  });

  fields.forEach((field, index) => {
    sheet.getColumn(index + 1).width = Math.max(12, Math.min(40, Math.round((field.width || 160) / 8)));
  });

  const summarySheet = workbook.addWorksheet('Summary');
  summarySheet.columns = [{ header: 'Metric', key: 'metric', width: 32 }, { header: 'Value', key: 'value', width: 20 }];
  Object.entries(summary)
    .filter(([, value]) => typeof value !== 'object')
    .forEach(([metric, value]) => summarySheet.addRow({ metric, value }));
  summarySheet.getRow(1).font = { bold: true };

  return workbook.xlsx.writeBuffer();
};

const writeTemplate = async (workspaceId, user) => {
  const config = await ensureDefaultTrackerConfig(workspaceId, user?._id);
  const fields = visibleFields(config).filter((field) => field.fieldType !== 'auto');
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Import Template');
  sheet.addRow(fields.map((field) => field.label));
  sheet.addRow(fields.map((field) => field.fieldKey));
  sheet.getRow(1).font = { bold: true };
  sheet.getRow(2).font = { italic: true, color: { argb: 'FF64748B' } };
  fields.forEach((field, index) => {
    sheet.getColumn(index + 1).width = Math.max(16, Math.min(36, Math.round((field.width || 160) / 8)));
  });
  return workbook.xlsx.writeBuffer();
};

const writePdf = async (workspaceId, user, filters = {}) => {
  const summary = await getSummaryReport(workspaceId, filters);
  const doc = new PDFDocument({ margin: 48 });
  const chunks = [];

  doc.on('data', (chunk) => chunks.push(chunk));
  const finished = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

  doc.fontSize(18).text('ONEPWS - Marketing Daily Tracker Summary');
  doc.moveDown(0.5).fontSize(10).fillColor('#475569').text(`Generated at: ${new Date().toLocaleString()}`);
  doc.text(`Generated by: ${user?.name || user?.email || 'System'}`);
  doc.moveDown();

  Object.entries(summary)
    .filter(([, value]) => typeof value !== 'object')
    .forEach(([metric, value]) => {
      doc.fillColor('#111827').fontSize(11).text(`${metric}: ${value}`);
    });

  doc.end();
  return finished;
};

module.exports = {
  writeWorkbook,
  writeTemplate,
  writePdf,
};
