const express = require('express');
const router = express.Router();

// ── Import all route modules ──────────────────────────────────────────────────
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const workspaceRoutes = require('./workspace.routes');
const departmentRoutes = require('./department.routes');
const designationRoutes = require('./designation.routes');
const employeeRoutes = require('./employee.routes');
const projectRoutes = require('./project.routes');
const milestoneRoutes = require('./milestone.routes');
const taskStageRoutes = require('./taskStage.routes');
const taskRoutes = require('./task.routes');
const subTaskRoutes = require('./subTask.routes');
const taskCommentRoutes = require('./taskComment.routes');
const taskAttachmentRoutes = require('./taskAttachment.routes');
const taskHistoryRoutes = require('./taskHistory.routes');
const taskTemplateRoutes = require('./taskTemplate.routes');
const taskDependencyRoutes = require('./taskDependency.routes');
const taskTimerRoutes = require('./taskTimer.routes');
const trackerRoutes = require('./tracker.routes');
const timesheetRoutes = require('./timesheet.routes');
const timeLogRoutes = require('./timeLog.routes');
const timerRoutes = require('./timer.routes');
const budgetRoutes = require('./budget.routes');
const budgetCategoryRoutes = require('./budgetCategory.routes');
const expenseRoutes = require('./expense.routes');
const paymentRoutes = require('./payment.routes');
const noteRoutes = require('./note.routes');
const noteFolderRoutes = require('./noteFolder.routes');
const calendarRoutes = require('./calendar.routes');
const holidayRoutes = require('./holiday.routes');
const mediaRoutes = require('./media.routes');
const momRoutes = require('./mom.routes');
const momTemplateRoutes = require('./momTemplate.routes');
const momController = require('../controllers/mom.controller');
const meetingRoutes = require('./meeting.routes');
const intakeFormRoutes = require('./intakeForm.routes');
const slaRoutes = require('./sla.routes');
const slaConfigRoutes = require('./slaConfig.routes');
const slaTrackerRoutes = require('./slaTracker.routes');
const slaEscalationRoutes = require('./slaEscalation.routes');
const approvalRoutes = require('./approval.routes');
const notificationRoutes = require('./notification.routes');
const notificationPreferenceRoutes = require('./notificationPreference.routes');
const notifTemplateRoutes = require('./notificationTemplate.routes');
const emailTemplateRoutes = require('./emailTemplate.routes');
const permissionRoutes = require('./permission.routes');
const wikiRoutes = require('./wiki.routes');
const vendorRoutes = require('./vendor.routes');
const announcementRoutes = require('./announcement.routes');
const feedbackRoutes = require('./feedback.routes');
const activityLogRoutes = require('./activityLog.routes');
const apiKeyRoutes = require('./apiKey.routes');
const webhookRoutes = require('./webhook.routes');
const webhookDeliveryRoutes = require('./webhookDelivery.routes');
const developerRoutes = require('./developer.routes');
const backupRoutes = require('./backup.routes');
const changelogRoutes = require('./changelog.routes');
const helpArticleRoutes = require('./helpArticle.routes');
const sprintRoutes = require('./sprint.routes');
const contentCalendarRoutes = require('./contentCalendar.routes');
const campaignRoutes = require('./campaign.routes');
const contentItemRoutes = require('./contentItem.routes');
const campaignTemplateRoutes = require('./campaignTemplate.routes');
const printJobRoutes = require('./printJob.routes');
const printQuotationRoutes = require('./printQuotation.routes');
const printProofRoutes = require('./printProof.routes');
const printDispatchRoutes = require('./printDispatch.routes');
const printReportRoutes = require('./printReport.routes');
const printTemplateRoutes = require('./printTemplate.routes');
const dashboardRoutes = require('./dashboard.routes');
const reportRoutes = require('./report.routes');
const reportScheduleRoutes = require('./reportSchedule.routes');
const settingsRoutes = require('./settings.routes');
const cronRoutes = require('./cron.routes');
const automationRoutes = require('./automation.routes');

// ── Health check ──────────────────────────────────────────────────────────────
router.get('/health', (req, res) => {
  res.json({ success: true, message: 'OnePWS API is running ✅', timestamp: new Date() });
});

// ── Mount routes ──────────────────────────────────────────────────────────────
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/workspaces/:wid', permissionRoutes);
router.use('/workspaces/:wid/departments', departmentRoutes);
router.use('/departments', departmentRoutes);
router.use('/workspaces/:wid/designations', designationRoutes);
router.use('/workspaces/:wid/employees', employeeRoutes);
router.use('/workspaces/:wid/projects', projectRoutes);
router.use('/projects', projectRoutes);
router.use('/workspaces/:wid/projects/:projectId/milestones', milestoneRoutes);
router.use('/milestones', milestoneRoutes);
router.use('/task-stages', taskStageRoutes);
router.use('/workspaces/:wid/task-stages', taskStageRoutes);
router.use('/tasks', taskRoutes);
router.use('/workspaces/:wid/tasks', taskRoutes);
router.use('/subtasks', subTaskRoutes);
router.use('/task-comments', taskCommentRoutes);
router.use('/task-attachments', taskAttachmentRoutes);
router.use('/task-history', taskHistoryRoutes);
router.use('/task-templates', taskTemplateRoutes);
router.use('/task-dependencies', taskDependencyRoutes);
router.use('/task-timers', taskTimerRoutes);
router.use('/workspaces/:wid/tracker', trackerRoutes);
router.use('/timesheets', timesheetRoutes);
router.use('/workspaces/:wid/timesheets', timesheetRoutes);
router.use('/workspaces/:wid/time-logs', timeLogRoutes);
router.use('/workspaces/:wid/timer', timerRoutes);
router.use('/workspaces/:wid/tasks/:taskId/timer', timerRoutes);
router.use('/budgets', budgetRoutes);
router.use('/expenses', expenseRoutes);
router.use('/workspaces/:wid/budgets', budgetRoutes);
router.use('/workspaces/:wid/budget', budgetRoutes);
router.use('/workspaces/:wid/budget-categories', budgetCategoryRoutes);
router.use('/workspaces/:wid/expenses', expenseRoutes);
router.use('/workspaces/:wid/expense', expenseRoutes);
router.use('/workspaces/:wid/payments', paymentRoutes);
router.use('/notes', noteRoutes);
router.use('/workspaces/:wid/notes', noteRoutes);
router.use('/workspaces/:wid/note-folders', noteFolderRoutes);
router.use('/workspaces/:wid/calendar', calendarRoutes);
router.use('/holidays', holidayRoutes);
router.use('/workspaces/:wid/holidays', holidayRoutes);
router.use('/workspaces/:wid/media', mediaRoutes);
router.use('/workspaces/:wid/moms', momRoutes);
router.use('/workspaces/:wid/mom-templates', momTemplateRoutes);
router.post(
  '/workspaces/:wid/meetings/:meetingId/create-mom',
  require('../middleware/auth.middleware').protect,
  require('../middleware/auth.middleware').verifyWorkspaceAccess,
  require('../middleware/auth.middleware').checkModuleEnabled('mom'),
  require('../middleware/auth.middleware').checkPermission('mom', 'create'),
  momController.createFromMeeting
);
router.use('/workspaces/:wid/meetings', meetingRoutes);
router.use('/intake-forms', intakeFormRoutes);
router.use('/sla', slaRoutes);
router.use('/workspaces/:wid/sla', slaRoutes);
router.use('/workspaces/:wid/sla-configs', slaConfigRoutes);
router.use('/workspaces/:wid/sla-trackers', slaTrackerRoutes);
router.use('/workspaces/:wid/tasks/:taskId/sla', slaRoutes);
router.use('/workspaces/:wid/sla-escalations', slaEscalationRoutes);
router.use('/approvals', approvalRoutes);
router.use('/notifications', notificationRoutes);
router.use('/workspaces/:wid/notification-preferences', notificationPreferenceRoutes);
router.use('/workspaces/:wid/notification-templates', notifTemplateRoutes);
router.use('/workspaces/:wid/email-templates', emailTemplateRoutes);
router.use('/wiki', wikiRoutes);
router.use('/workspaces/:wid/wiki', wikiRoutes);
router.use('/vendors', vendorRoutes);
router.use('/announcements', announcementRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/api-keys', apiKeyRoutes);
router.use('/workspaces/:wid/api-keys', apiKeyRoutes);
router.use('/workspaces/:wid/webhooks', webhookRoutes);
router.use('/workspaces/:wid/webhook-deliveries', webhookDeliveryRoutes);
router.use('/workspaces/:wid/developer', developerRoutes);
router.use('/backups', backupRoutes);
router.use('/changelog', changelogRoutes);
router.use('/help', helpArticleRoutes);
router.use('/sprints', sprintRoutes);
router.use('/content-calendar', contentCalendarRoutes);
router.use('/workspaces/:wid/content-calendar', contentCalendarRoutes);
router.use('/content-items', contentItemRoutes);
router.use('/workspaces/:wid/content-items', contentItemRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/workspaces/:wid/campaigns', campaignRoutes);
router.use('/campaign-templates', campaignTemplateRoutes);
router.use('/workspaces/:wid/campaign-templates', campaignTemplateRoutes);
router.use('/print-jobs', printJobRoutes);
router.use('/workspaces/:wid/print-jobs', printJobRoutes);
router.use('/print-quotations', printQuotationRoutes);
router.use('/workspaces/:wid/print-quotations', printQuotationRoutes);
router.use('/print-proofs', printProofRoutes);
router.use('/workspaces/:wid/print-proofs', printProofRoutes);
router.use('/print-dispatches', printDispatchRoutes);
router.use('/workspaces/:wid/print-dispatches', printDispatchRoutes);
router.use('/workspaces/:wid/print-reports', printReportRoutes);
router.use('/print-templates', printTemplateRoutes);
router.use('/workspaces/:wid/print-templates', printTemplateRoutes);
router.use('/workspaces/:wid/dashboard', dashboardRoutes);
router.use('/workspaces/:wid/reports', reportRoutes);
router.use('/workspaces/:wid/report-schedules', reportScheduleRoutes);
router.use('/settings', settingsRoutes);
router.use('/workspaces/:wid/settings', settingsRoutes);
router.use('/workspaces/:wid/automation', automationRoutes);
router.use('/admin/cron', cronRoutes);

module.exports = router;
