const express = require('express');
const router = express.Router();

// ── Import all route modules ──────────────────────────────────────────────────
const authRoutes = require('./auth.routes');
const userRoutes = require('./user.routes');
const workspaceRoutes = require('./workspace.routes');
const departmentRoutes = require('./department.routes');
const projectRoutes = require('./project.routes');
const milestoneRoutes = require('./milestone.routes');
const taskStageRoutes = require('./taskStage.routes');
const taskRoutes = require('./task.routes');
const subTaskRoutes = require('./subTask.routes');
const taskCommentRoutes = require('./taskComment.routes');
const taskAttachmentRoutes = require('./taskAttachment.routes');
const taskHistoryRoutes = require('./taskHistory.routes');
const taskTemplateRoutes = require('./taskTemplate.routes');
const taskDependencyRoutes = require('./taskDependency.routes');
const taskTimerRoutes = require('./taskTimer.routes');
const trackerRoutes = require('./tracker.routes');
const timesheetRoutes = require('./timesheet.routes');
const budgetRoutes = require('./budget.routes');
const expenseRoutes = require('./expense.routes');
const noteRoutes = require('./note.routes');
const calendarRoutes = require('./calendar.routes');
const holidayRoutes = require('./holiday.routes');
const mediaRoutes = require('./media.routes');
const momRoutes = require('./mom.routes');
const meetingRoutes = require('./meeting.routes');
const intakeFormRoutes = require('./intakeForm.routes');
const slaRoutes = require('./sla.routes');
const approvalRoutes = require('./approval.routes');
const notificationRoutes = require('./notification.routes');
const notificationPreferenceRoutes = require('./notificationPreference.routes');
const notifTemplateRoutes = require('./notificationTemplate.routes');
const emailTemplateRoutes = require('./emailTemplate.routes');
const permissionRoutes = require('./permission.routes');
const wikiRoutes = require('./wiki.routes');
const vendorRoutes = require('./vendor.routes');
const announcementRoutes = require('./announcement.routes');
const feedbackRoutes = require('./feedback.routes');
const activityLogRoutes = require('./activityLog.routes');
const apiKeyRoutes = require('./apiKey.routes');
const backupRoutes = require('./backup.routes');
const changelogRoutes = require('./changelog.routes');
const helpArticleRoutes = require('./helpArticle.routes');
const sprintRoutes = require('./sprint.routes');
const contentCalendarRoutes = require('./contentCalendar.routes');
const campaignRoutes = require('./campaign.routes');
const reportRoutes = require('./report.routes');
const reportScheduleRoutes = require('./reportSchedule.routes');
const settingsRoutes = require('./settings.routes');

// ── Health check ──────────────────────────────────────────────────────────────
router.get('/health', (req, res) => {
  res.json({ success: true, message: 'OnePWS API is running ✅', timestamp: new Date() });
});

// ── Mount routes ──────────────────────────────────────────────────────────────
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/workspaces/:wid', permissionRoutes);
router.use('/departments', departmentRoutes);
router.use('/projects', projectRoutes);
router.use('/milestones', milestoneRoutes);
router.use('/task-stages', taskStageRoutes);
router.use('/tasks', taskRoutes);
router.use('/workspaces/:wid/tasks', taskRoutes);
router.use('/subtasks', subTaskRoutes);
router.use('/task-comments', taskCommentRoutes);
router.use('/task-attachments', taskAttachmentRoutes);
router.use('/task-history', taskHistoryRoutes);
router.use('/task-templates', taskTemplateRoutes);
router.use('/task-dependencies', taskDependencyRoutes);
router.use('/task-timers', taskTimerRoutes);
router.use('/workspaces/:wid/tracker', trackerRoutes);
router.use('/timesheets', timesheetRoutes);
router.use('/budgets', budgetRoutes);
router.use('/expenses', expenseRoutes);
router.use('/workspaces/:wid/budgets', budgetRoutes);
router.use('/workspaces/:wid/expenses', expenseRoutes);
router.use('/notes', noteRoutes);
router.use('/workspaces/:wid/calendar', calendarRoutes);
router.use('/holidays', holidayRoutes);
router.use('/workspaces/:wid/holidays', holidayRoutes);
router.use('/workspaces/:wid/media', mediaRoutes);
router.use('/workspaces/:wid/moms', momRoutes);
router.use('/workspaces/:wid/meetings', meetingRoutes);
router.use('/intake-forms', intakeFormRoutes);
router.use('/sla', slaRoutes);
router.use('/workspaces/:wid/sla', slaRoutes);
router.use('/approvals', approvalRoutes);
router.use('/notifications', notificationRoutes);
router.use('/workspaces/:wid/notification-preferences', notificationPreferenceRoutes);
router.use('/workspaces/:wid/notification-templates', notifTemplateRoutes);
router.use('/workspaces/:wid/email-templates', emailTemplateRoutes);
router.use('/wiki', wikiRoutes);
router.use('/vendors', vendorRoutes);
router.use('/announcements', announcementRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/api-keys', apiKeyRoutes);
router.use('/backups', backupRoutes);
router.use('/changelog', changelogRoutes);
router.use('/help', helpArticleRoutes);
router.use('/sprints', sprintRoutes);
router.use('/content-calendar', contentCalendarRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/workspaces/:wid/reports', reportRoutes);
router.use('/workspaces/:wid/report-schedules', reportScheduleRoutes);
router.use('/settings', settingsRoutes);
router.use('/workspaces/:wid/settings', settingsRoutes);

module.exports = router;
