const express = require('express');
const router = express.Router({ mergeParams: true });
const { protect, verifyWorkspaceAccess } = require('../middleware/auth.middleware');
const ctrl = require('../controllers/wiki.controller');

router.use(protect);
router.use((req, res, next) => (req.params.wid ? verifyWorkspaceAccess(req, res, next) : next()));

router.get('/home', ctrl.home);
router.get('/search', ctrl.search);
router.get('/my-drafts', (req, res, next) => { req.query.status = 'draft'; next(); }, ctrl.list);
router.get('/pending-reviews', (req, res, next) => { req.query.status = 'pending_review'; next(); }, ctrl.list);
router.get('/needs-update', (req, res, next) => { req.query.status = 'needs_update'; next(); }, ctrl.list);
router.get('/popular', (req, res, next) => { req.query.normal = 'false'; next(); }, ctrl.list);
router.get('/reports', ctrl.reports);
router.post('/reports/export/pdf', ctrl.exportReports);
router.post('/reports/export/excel', ctrl.exportReports);
router.post('/export/bulk', ctrl.bulkExport);

router.get('/categories', ctrl.categories);
router.post('/categories', ctrl.createCategory);
router.patch('/categories/reorder', ctrl.categories);
router.get('/categories/:categoryId', ctrl.getCategory);
router.put('/categories/:categoryId', ctrl.updateCategory);
router.delete('/categories/:categoryId', ctrl.deleteCategory);
router.patch('/categories/:categoryId/archive', ctrl.deleteCategory);
router.patch('/categories/:categoryId/restore', ctrl.updateCategory);
router.patch('/categories/:categoryId/move', ctrl.updateCategory);
router.get('/categories/:categoryId/articles', ctrl.categoryArticles);

router.get('/templates', ctrl.templates);
router.post('/templates', ctrl.createTemplate);
router.get('/templates/:templateId', ctrl.getTemplate);
router.put('/templates/:templateId', ctrl.updateTemplate);
router.delete('/templates/:templateId', ctrl.deleteTemplate);
router.patch('/templates/:templateId/set-default', ctrl.setDefaultTemplate);
router.post('/templates/:templateId/clone', ctrl.cloneTemplate);
router.post('/templates/:templateId/create-article', ctrl.create);

router.get('/articles', ctrl.list);
router.post('/articles', ctrl.create);
router.get('/articles/:articleId', ctrl.getById);
router.put('/articles/:articleId', ctrl.update);
router.delete('/articles/:articleId', ctrl.remove);
router.post('/articles/:articleId/submit-review', ctrl.submitReview);
router.patch('/articles/:articleId/approve', ctrl.approve);
router.patch('/articles/:articleId/reject', ctrl.reject);
router.patch('/articles/:articleId/publish', ctrl.publish);
router.patch('/articles/:articleId/needs-update', ctrl.needsUpdate);
router.patch('/articles/:articleId/archive', ctrl.archive);
router.patch('/articles/:articleId/deprecate', ctrl.deprecate);
router.patch('/articles/:articleId/restore', ctrl.restore);
router.patch('/articles/:articleId/pin', ctrl.pin);
router.patch('/articles/:articleId/unpin', ctrl.unpin);
router.patch('/articles/:articleId/feature', ctrl.feature);
router.patch('/articles/:articleId/unfeature', ctrl.unfeature);
router.get('/articles/:articleId/versions', ctrl.versions);
router.post('/articles/:articleId/versions', ctrl.createVersion);
router.post('/articles/:articleId/versions/:versionId/restore', ctrl.restoreVersion);
router.post('/articles/:articleId/attachments', ctrl.addAttachment);
router.get('/articles/:articleId/attachments', ctrl.getById);
router.delete('/articles/:articleId/attachments/:attachmentId', ctrl.removeAttachment);
router.post('/articles/:articleId/related', ctrl.addRelated);
router.delete('/articles/:articleId/related/:relatedArticleId', ctrl.removeRelated);
router.get('/articles/:articleId/comments', ctrl.comments);
router.post('/articles/:articleId/comments', ctrl.addComment);
router.put('/articles/:articleId/comments/:commentId', ctrl.updateComment);
router.delete('/articles/:articleId/comments/:commentId', ctrl.deleteComment);
router.patch('/articles/:articleId/comments/:commentId/resolve', ctrl.resolveComment);
router.post('/articles/:articleId/feedback', ctrl.feedback);
router.get('/articles/:articleId/activity', ctrl.activity);
router.get('/articles/:articleId/export/pdf', ctrl.exportPdf);
router.get('/articles/:articleId/export/html', ctrl.exportHtml);
router.get('/articles/:articleId/export/markdown', ctrl.exportMarkdown);

router.get('/', ctrl.list);
router.post('/', ctrl.create);
router.get('/:articleId', ctrl.getById);
router.put('/:articleId', ctrl.update);
router.delete('/:articleId', ctrl.remove);

module.exports = router;
