const mongoose = require('mongoose');

const NOTIFICATION_EVENTS = [
  'task_assigned',
  'task_updated',
  'task_stage_changed',
  'task_commented',
  'task_overdue',
  'task_due_today',
  'task_due_tomorrow',
  'mention',
  'task_mentioned',
  'task_created',
  'task_completed',
  'task_reopened',
  'task_approval_requested',
  'task_auto_hold',
  'task_auto_closed',
  'project_assigned',
  'project_status_changed',
  'project_due_in_3_days',
  'project_due_today',
  'project_overdue',
  'workspace_invited',
  'user_joined_workspace',
  'mom_created',
  'mom_sent_for_signature',
  'mom_signed',
  'mom_pending_signature',
  'mom_completed',
  'mom_pdf_generated',
  'mom_point_due',
  'mom_point_overdue',
  'meeting_scheduled',
  'meeting_updated',
  'meeting_rescheduled',
  'meeting_cancelled',
  'meeting_reminder',
  'meeting_completed',
  'meeting_attendee_responded',
  'mom_required_after_meeting',
  'calendar_reminder',
  'deadline_approaching',
  'sla_phase_due',
  'sla_phase_overdue',
  'sla_phase_completed',
  'sla_breach',
  'sla_escalation',
  'sla_feedback_requested',
  'sla_t0_reset',
  'budget_submitted',
  'budget_approval_requested',
  'budget_approved',
  'budget_rejected',
  'budget_threshold_crossed',
  'budget_overrun',
  'budget_over_budget',
  'expense_approval_requested',
  'expense_submitted',
  'expense_approved',
  'expense_rejected',
  'expense_payment_due',
  'timesheet_submitted',
  'timesheet_approved',
  'timesheet_rejected',
  'tracker_row_created',
  'tracker_row_assigned',
  'tracker_row_updated',
  'tracker_task_delayed',
  'tracker_task_assigned',
  'tracker_delay_alert',
  'tracker_row_submitted',
  'tracker_row_locked',
  'tracker_import_completed',
  'intake_submitted',
  'intake_approved',
  'intake_rejected',
  'intake_review_pending',
  'intake_auto_rejected',
  't0_confirmed',
  'calendar_event_created',
  'calendar_event_updated',
  'calendar_event_cancelled',
  'calendar_event_reminder',
  'employee_invited',
  'note_mentioned',
  'note_shared',
  'wiki_review_requested',
  'wiki_article_approved',
  'wiki_article_rejected',
  'wiki_review_due',
  'campaign_created',
  'campaign_assigned',
  'campaign_approval_requested',
  'campaign_approved',
  'campaign_rejected',
  'campaign_started',
  'campaign_completed',
  'campaign_cancelled',
  'content_created',
  'content_assigned',
  'content_due_tomorrow',
  'content_due_today',
  'content_overdue',
  'content_approval_requested',
  'content_approved',
  'content_rejected',
  'content_scheduled',
  'content_published',
  'content_performance_pending',
  'performance_updated',
  'print_job_created',
  'print_job_assigned',
  'artwork_uploaded',
  'artwork_approval_requested',
  'artwork_approved',
  'artwork_rejected',
  'quotation_received',
  'quotation_selected',
  'print_approval_requested',
  'print_approved',
  'sent_to_vendor',
  'proof_uploaded',
  'proof_approved',
  'proof_rejected',
  'production_started',
  'production_completed',
  'ready_for_dispatch',
  'print_dispatched',
  'print_delivered',
  'quality_check_required',
  'quality_issue_reported',
  'reprint_required',
  'print_job_completed',
  'print_job_overdue',
  'print_due_today',
  'print_due_tomorrow',
  'announcement',
  'announcement_created',
  'daily_digest',
  'system',
  'system_backup_completed',
  'system_backup_failed',
  'security_failed_login'
];

const channelStatusSchema = new mongoose.Schema(
  {
    sent: { type: Boolean, default: false },
    sentAt: Date,
    error: String
  },
  { _id: false }
);

const schema = new mongoose.Schema(
  {
    workspace: { type: mongoose.Schema.Types.ObjectId, ref: 'Workspace', required: true },
    recipient: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    sender: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    type: { type: String, enum: NOTIFICATION_EVENTS, required: true },
    title: { type: String, required: true, trim: true },
    message: { type: String, required: true },
    shortMessage: String,
    refModel: String,
    refId: { type: mongoose.Schema.Types.ObjectId },
    actionUrl: String,
    priority: { type: String, enum: ['low', 'normal', 'medium', 'high', 'urgent'], default: 'normal' },
    channels: {
      inApp: { type: Boolean, default: true },
      email: { type: Boolean, default: false },
      slack: { type: Boolean, default: false },
      telegram: { type: Boolean, default: false }
    },
    deliveryStatus: {
      inApp: { type: channelStatusSchema, default: () => ({}) },
      email: { type: channelStatusSchema, default: () => ({}) },
      slack: { type: channelStatusSchema, default: () => ({}) },
      telegram: { type: channelStatusSchema, default: () => ({}) }
    },
    isRead: { type: Boolean, default: false },
    readAt: Date,
    isArchived: { type: Boolean, default: false },
    archivedAt: Date,
    metadata: {
      taskNumber: String,
      taskTitle: String,
      projectName: String,
      departmentName: String,
      dueDate: Date,
      delayDays: Number,
      amount: Number,
      meetingDate: Date,
      meetingLink: String,
      momNumber: String,
      momTitle: String,
      slaPhase: String,
      escalationLevel: String
    }
  },
  { timestamps: true }
);

schema.index({ recipient: 1, isRead: 1, createdAt: -1 });
schema.index({ workspace: 1, createdAt: -1 });
schema.index({ workspace: 1, type: 1 });
schema.index({ refModel: 1, refId: 1 });

module.exports = mongoose.models.Notification || mongoose.model('Notification', schema);
module.exports.NOTIFICATION_EVENTS = NOTIFICATION_EVENTS;
