const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  workspace: { type: mongoose.Schema.Types.ObjectId, ref: "Workspace", required: true },
  project: { type: mongoose.Schema.Types.ObjectId, ref: "Project" },
  taskNumber: { type: String, unique: true },
  title: { type: String, required: true },
  description: String,
  taskCategory: { type: String, enum: ["Catalogue", "Brochure", "Flyer", "Social Media", "PPT", "Email Campaign", "Website Update", "Events", "Other"] },
  deliverableType: { type: String, enum: ["CAT-S", "CAT-M", "CAT-L", "BROCHURE", "FLYER", "SOCIAL", "PPT-S", "PPT-L", "EMAIL", "EVENT", "WEB", "OTHER"] },
  requestType: { type: String, enum: ["new_work", "rework"], default: "new_work" },
  revisionNumber: { type: String, default: "R0" },
  stage: { type: mongoose.Schema.Types.ObjectId, ref: "TaskStage" },
  status: { type: String, enum: ["open", "in_process", "review", "hold", "closed", "cancelled"], default: "open" },
  priority: { type: String, enum: ["low", "medium", "high", "urgent"], default: "medium" },
  requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  requestedByDepartment: { type: mongoose.Schema.Types.ObjectId, ref: "Department" },
  assignedTo: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  handledBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  watchers: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  taskProvidedBy: String,
  taskGivenByDepartmentText: String,
  productType: { type: String, enum: ["CD", "CCR", "MOT", "FLOOR", "Other"] },
  receiptDate: Date,
  finalInputReceiptDate: Date,
  targetDueDate: Date,
  actualClosingDate: Date,
  delayInDays: Number,
  delayStatus: { type: String, enum: ["on_time", "delayed", "early", "pending"], default: "pending" },
  estimatedHours: Number, loggedHours: Number,
  dueDate: Date, startDate: Date, completedAt: Date,
  isOverdue: Boolean, isLocked: Boolean, isDeleted: { type: Boolean, default: false },
  holdReason: String,
  holdStartDate: Date,
  feedback: {
    required: Boolean,
    requestedAt: Date,
    dueAt: Date,
    receivedAt: Date,
    status: { type: String, enum: ['none', 'requested', 'received'], default: 'none' }
  },
  remarkIfPending: String,
  finalStatus: { type: String, enum: ["pending", "submitted", "closed"], default: "pending" },
  tags: [String],
  customFields: { type: Map, of: mongoose.Schema.Types.Mixed },
  intakeForm: { type: mongoose.Schema.Types.ObjectId, ref: "IntakeForm" },
  slaTracker: { type: mongoose.Schema.Types.ObjectId, ref: "SLATracker" },
  calendarEvent: { type: mongoose.Schema.Types.ObjectId, ref: "CalendarEvent" },
  publicShare: { enabled: Boolean, token: String, expiresAt: Date },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" }
}, { timestamps: true });

module.exports = mongoose.models.Task || mongoose.model('Task', schema);
