const mongoose = require('mongoose');

const { Schema } = mongoose;

const workspaceSettingsSchema = new Schema(
  {
    workspace: { type: Schema.Types.ObjectId, ref: 'Workspace', required: true, unique: true },
    general: {
      workspaceName: String,
      companyName: String,
      description: String,
      timezone: { type: String, default: 'Asia/Kolkata' },
      dateFormat: { type: String, default: 'DD-MM-YYYY' },
      timeFormat: { type: String, enum: ['12h', '24h'], default: '12h' },
      currency: { type: String, default: 'INR' },
      financialYearStartMonth: { type: Number, default: 4 },
      weekStartDay: { type: String, enum: ['monday', 'sunday'], default: 'monday' },
    },
    branding: {
      primaryColor: String,
      secondaryColor: String,
      accentColor: String,
      logoLight: String,
      logoDark: String,
      favicon: String,
      emailLogo: String,
      reportLogo: String,
      fontFamily: String,
      customCss: String,
    },
    modules: {
      dashboard: { type: Boolean, default: true },
      projects: { type: Boolean, default: true },
      tasks: { type: Boolean, default: true },
      tracker: { type: Boolean, default: true },
      calendar: { type: Boolean, default: true },
      notifications: { type: Boolean, default: true },
      reports: { type: Boolean, default: true },
      media: { type: Boolean, default: true },
      meetings: { type: Boolean, default: true },
      mom: { type: Boolean, default: true },
      sla: { type: Boolean, default: true },
      intake: { type: Boolean, default: true },
      budget: { type: Boolean, default: false },
      expenses: { type: Boolean, default: false },
      timesheets: { type: Boolean, default: false },
      notes: { type: Boolean, default: true },
      wiki: { type: Boolean, default: false },
      vendors: { type: Boolean, default: false },
      campaigns: { type: Boolean, default: false },
      approvals: { type: Boolean, default: false },
      settings: { type: Boolean, default: true },
    },
    workingDays: {
      monday: { type: Boolean, default: true },
      tuesday: { type: Boolean, default: true },
      wednesday: { type: Boolean, default: true },
      thursday: { type: Boolean, default: true },
      friday: { type: Boolean, default: true },
      saturday: { type: Boolean, default: false },
      sunday: { type: Boolean, default: false },
    },
    workingHours: {
      start: { type: String, default: '10:00' },
      end: { type: String, default: '18:00' },
    },
    tasks: { type: Schema.Types.Mixed, default: {} },
    tracker: { type: Schema.Types.Mixed, default: {} },
    calendar: { type: Schema.Types.Mixed, default: {} },
    reports: { type: Schema.Types.Mixed, default: {} },
    media: { type: Schema.Types.Mixed, default: {} },
    meetings: { type: Schema.Types.Mixed, default: {} },
    mom: { type: Schema.Types.Mixed, default: {} },
    sla: { type: Schema.Types.Mixed, default: {} },
    budgetExpenses: { type: Schema.Types.Mixed, default: {} },
    notes: { type: Schema.Types.Mixed, default: {} },
    backup: { type: Schema.Types.Mixed, default: {} },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User' },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

module.exports = mongoose.models.WorkspaceSettings || mongoose.model('WorkspaceSettings', workspaceSettingsSchema);
